### PR TITLE
Polish drag and edit interactions

### LINKED ISSUE #208: Markdown (Text) elements restrict movement to edge
- Restrict dragging of markdown elements to a 16px edge around the element
- Allow for a single click after selection to change into edit mode
- It is not expected to be able to drag and resize when in edit mode

### PR DESCRIPTION
**Pull request by fritz-c**
### Description

Some slight fixes to dragging and editing behavior that make it feel more responsive all around.
Fixes #208 

#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by gksander** [comment]
The dragging feels good. I'm having troubles clicking to edit the text in the deploy preview though. Should I be able to click/focus the text element to start editing it?

spec-editor

**Comment by fritz-c** [comment]
Ah shoot, forgot to take nested elements into account. Will work on it (probably just a matter of adding an `event.stopPropagation()`.

**Comment by fritz-c** [comment]
Fixed the nested element issue now.

**Review by gksander — APPROVED** [review]
LGTM

**Pull request merged**
